version: '3'

services:
  orders-db:
    container_name: orders-database
    image: postgres:16.2
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/dat
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ordersdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456